-- Add new DeviceType enum values
ALTER TYPE "DeviceType" ADD VALUE IF NOT EXISTS 'NINTENDO';
ALTER TYPE "DeviceType" ADD VALUE IF NOT EXISTS 'STEAM_DECK';
ALTER TYPE "DeviceType" ADD VALUE IF NOT EXISTS 'PC';

-- Add new ControlMethod enum values
ALTER TYPE "ControlMethod" ADD VALUE IF NOT EXISTS 'DNS_FILTERING';
ALTER TYPE "ControlMethod" ADD VALUE IF NOT EXISTS 'ROUTER_GATEWAY';
ALTER TYPE "ControlMethod" ADD VALUE IF NOT EXISTS 'XBOX_ACCOUNT';
ALTER TYPE "ControlMethod" ADD VALUE IF NOT EXISTS 'OFFICIAL_PARENTAL_GUIDE';
